SET C51INC=C:\Keil_c51\C51\Inc;C:\Keil_c51\C51\Inc\Atmel
SET C51LIB=C:\Keil_c51\C51\Lib
SET CPU_TYPE=AT89C52
SET CPU_VENDOR=Atmel
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"C:\Keil_c51\C51\BIN\C51.EXE" @.\Objects\delay.__i
"C:\Keil_c51\C51\BIN\C51.EXE" @.\Objects\GPIO.__i
"C:\Keil_c51\C51\BIN\C51.EXE" @.\Objects\main.__i
"C:\Keil_c51\C51\BIN\C51.EXE" @.\Objects\timer.__i
"C:\Keil_c51\C51\BIN\C51.EXE" @.\Objects\USART1.__i
"C:\Keil_c51\C51\BIN\C51.EXE" @.\Objects\misc.__i
"C:\Keil_c51\C51\BIN\C51.EXE" @.\Objects\ADC.__i
"C:\Keil_c51\C51\BIN\C51.EXE" @.\Objects\dlt645.__i
"C:\Keil_c51\C51\BIN\C51.EXE" @.\Objects\rs485.__i
"C:\Keil_c51\C51\BIN\BL51.EXE" @.\Objects\SMARTS~1.LNP
"C:\Keil_c51\C51\BIN\OH51.EXE" ".\Objects\SmartSwitch" 
H:\SmartSwitch_Project\smartswitch\Project\DelTempFile_CopyHex.bat
